macro(add_yaml target)
    find_package(yaml-cpp REQUIRED)
    target_link_libraries(${target} PRIVATE yaml-cpp)
endmacro()

macro(add_thread target)
    find_package(Threads REQUIRED)
    target_link_libraries(${target} PRIVATE Threads::Threads)
endmacro()

macro(add_opencv target)
    find_package(OpenCV REQUIRED)
    target_link_libraries(${target} PRIVATE ${OpenCV_LIBS})
endmacro()

macro(add_pcl target)
    target_compile_options(${target} PRIVATE -Wno-dev)
    find_package(PCL REQUIRED)
    target_link_libraries(${target} PRIVATE ${PCL_LIBRARIES})
endmacro()

macro(add_zed target)
    find_package(ZED REQUIRED)
    target_link_libraries(${target} PRIVATE ${ZED_LIBRARIES})
    target_include_directories(${target} PRIVATE ${ZED_INCLUDE_DIRS})
endmacro()

macro(add_k4a target)
    find_package(k4a REQUIRED)
    target_link_libraries(${target} PUBLIC k4a)
endmacro()

macro(add_slamtec name include_dirs)
    target_include_directories(${name} PUBLIC ${PROJECT_SOURCE_DIR}/slamtec/include/)
    link_directories(${PROJECT_SOURCE_DIR}/slamtec/share/)
    target_link_libraries(${name} PUBLIC ${PROJECT_SOURCE_DIR}/slamtec/share/libsl_lidar_sdk.a)
endmacro()

macro(add_cuda target)
    find_package(CUDA 11.4 REQUIRED)
    target_link_libraries(${target} PUBLIC ${CUDA_LIBRARIES})
    message("CUDA_LIBRARIES:${CUDA_LIBRARIES}")
    message("CUDA_INCLUDE_DIRS:${CUDA_INCLUDE_DIRS}")
    list(APPEND ${include_dirs} ${CUDA_INCLUDE_DIRS})
endmacro()
